name: ersa_apps
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  # sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.3
  flutter_bloc: ^3.0.0
  cloud_firestore: ^2.0.0
  firebase_core: ^1.3.0
  firebase_storage: ^9.0.0
  http: ^0.13.3
  file_picker: ^3.0.3
  flutter_plugin_android_lifecycle: ^2.0.0
  plugin_platform_interface: ^2.0.0
  page_transition: "^2.0.2"
  path_provider: ^2.0.2 
  image_picker: ^0.8.1+3
  ext_storage: ^1.0.3
  progress_dialog: ^1.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  